config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [ :index, :show, :create, :new ] do
    resources :reviews, only: [ :index, :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"].freeze
  validates :name, :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = Review.where(restaurant_id: @restaurant)
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<%= link_to 'Add Restaurant', new_restaurant_path, class: 'm-1 d-block btn btn-primary text-right'%>
<% @restaurants.each do |r| %>
<div class="card m-1 p-1">
  <h3><%= link_to r.name, restaurant_path(r), class: 'text-decoration-none' %></h3>
  <p><%= r.category.capitalize %> food </p>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :phone_number %>
  <%= f.input :address %>
  <%= f.input :category, as: :select, collection: Restaurant::CATEGORIES %>
  <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h3><%= @restaurant.category %> food</h3>
<h2>Address: <%= @restaurant.address %></h2>
<h2>Contact: <%= @restaurant.phone_number %></h2>
<%= link_to 'Back', restaurants_path  %>
<%= link_to 'Add Review', new_restaurant_review_path(@restaurant)  %>
<%= link_to 'Reviews', restaurant_reviews_path(@restaurant) %>

app/views/reviews/index.html.erb
<% @reviews.each do |r| %><ol>
  <li><%= r.rating * '⭐' %>
    <p><%= r.content %></p>
  </li>
</ol>
<% end %>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review] do |f| %>
  <%= f.input :rating, as: :select,  collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit "Publish Review", class: "btn btn-info"%>
<% end %>